export const CLEAR_DATA = "CLEAR_DATA";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_ALL_BOXES = "GET_ALL_BOXES";
export const CREATE_BOX = "CREATE_BOX";
export const GET_BOX = "GET_BOX";
export const UPDATE_BOX = "UPDATE_BOX";
export const DELETE_BOX = "DELETE_BOX";

export const GET_ALL_SPECIFICATIONS = "GET_ALL_SPECIFICATIONS";
export const CREATE_SPECIFICATION = "CREATE_SPECIFICATION";
export const GET_SPECIFICATION = "GET_SPECIFICATION";
export const UPDATE_SPECIFICATION = "UPDATE_SPECIFICATION";
export const DELETE_SPECIFICATION = "DELETE_SPECIFICATION";

export const CREATE_PRODUCT_SPECIFICATION = "CREATE_PRODUCT_SPECIFICATION";
export const UPDATE_PRODUCT_SPECIFICATION = "UPDATE_PRODUCT_SPECIFICATION";
export const DELETE_PRODUCT_SPECIFICATION = "DELETE_PRODUCT_SPECIFICATION";

export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const GET_COMMENT = "GET_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
